homeassistant:
  name: !secret name
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret timezone

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml

python_script:

logger:
  default: warning
  logs:
    homeassistant.components.python_script.growlights.py: info
    homeassistant.components.python_script.humidifier.py: info

sun:

input_boolean:
  can_enable_growlights:
    name: "Growlight Permissive"
    initial: on
  growlight_on:
    name: "Growlight Status"
    initial: off
  humidifier_on:
    name: "Humidifier Status"
    initial: off

input_number:
  growlight_cycles:
    name: "Growlight Cycles"
    min: 0
    max: 17280
    mode: box
  growlight_hysteresis:
    name: "Growlight Setpoint Hysteresis"
    min: 0
    max: 50
    step: 5
    mode: slider
    unit_of_measurement: "lux"
  growlight_percent:
    name: "Growlight Accumulated Light"
    min: 0
    max: 200
    unit_of_measurement: "%"
  growlight_period:
    name: "Growlight Period"
    min: 5
    max: 60
    step: 1
    initial: 10
    mode: box
    unit_of_measurement: "s"
  light_setpoint:
    name: "Growlight Setpoint"
    min: 0
    max: 24
    step: 0.25
    mode: box
    unit_of_measurement: "hrs"
  light_threshold:
    name: "Growlight Threshold"
    min: 0
    max: 1000
    mode: box
    unit_of_measurement: "lux"
  humidity_setpoint:
    name: "Humidity Level"
    min: 0
    max: 100
    mode: box
    step: 1
    unit_of_measurement: "RH"
  humidity_offset:
    name: "Humidity Offset"
    min: -100
    max: 100
    mode: box
    unit_of_measurement: "RH"
